it('Testing untuk Admin', function() {
    cy.visit('http://localhost:5173/')
    
    cy.get('#root a[href="/login"]').click();
    cy.get('#root [name="email"]').click();
    cy.get('#root [name="email"]').type('dhe@gmail.com');
    cy.get('#root [name="password"]').click();
    cy.get('#root [name="password"]').type('denydeny');
    cy.get('#root button.rounded').click();
    cy.get('#root input.border').click();
    cy.get('#root input.border').type('mod');
    cy.get('#root div.text-muted-foreground.truncate').click();
    cy.get('#root div:nth-child(5) button:nth-child(1)').click();
    cy.get('#root div:nth-child(2) > h3.font-semibold > a.no-underline').click();
    cy.get('#root [name="content"]').click();
    cy.get('#root [name="content"]').type('hahahahahahahahahaha');
    cy.get('#root button.rounded').click();
    cy.get('#root div.gap-4.items-center.text-muted-foreground button:nth-child(1)').click();
    cy.get('#root form > div:nth-child(1)').click();
    cy.get('#root label:nth-child(4) span').click();
    cy.get('#root label:nth-child(4) [name="reason"]').check();
    cy.get('#root div:nth-child(4) button.text-white').click();
    cy.get('#root button.border').click();
    cy.get('#radix-_r_0_ button.border').click();
    cy.get('#root button.text-primary').click();
    cy.get('#root textarea.min-h-25').click();
    cy.get('#root textarea.min-h-25').type('wkwkwkwkwkw');
    cy.get('#root button.font-semibold').click();
    cy.get('#root button.border').click();
    cy.get('#radix-_r_3_ button.border').click();
    cy.get('#root div.flex-wrap.text-muted-foreground button.hover\\:text-red-400').click();
    cy.get('#root button.flex.font-medium').click();
    cy.get('#root a.hover\\:bg-emerald-950\\/40').click();
    cy.get('#root div.flex-wrap button:nth-child(2)').click();
    cy.get('#root button:nth-child(3)').click();
    cy.get('#root button:nth-child(4)').click();
    cy.get('#root button:nth-child(5)').click();
    cy.get('#root div.bg-card.gap-4').click();
    cy.get('#root div.flex-wrap button:nth-child(2)').click();
    cy.get('#root div.cursor-pointer').click();
    cy.get('#root textarea.border').click();
    cy.get('#root textarea.border').type('iyaaa');
    cy.get('#root button.bg-emerald-600').click();
    cy.get('#root div.flex-wrap button:nth-child(1)').click();
    cy.get('#root input.border').click();
    cy.get('#root input.border').click();
    cy.get('#root a[href="/notifications"]').click();
    cy.get('#root button.hover\\:underline').click();
    cy.get('#root div:nth-child(5) a.rounded').click();
    cy.get('#root a[href="/notifications"]').click();
    cy.get('#root div:nth-child(2) > div.gap-2 > button.rounded > svg').click();
    cy.get('#root a.flex span').click();
    cy.get('#root button.border').click();
    cy.get('[name="username"]').click();
    cy.get('[name="username"]').clear();
    cy.get('[name="username"]').type('denisaa');
    cy.get('[name="bio"]').click();
    cy.get('[name="bio"]').type('ss');
    cy.get('#root button[type="submit"]').click();
    cy.get('#root div:nth-child(1) > button:nth-child(2)').click();
    cy.get('#root div:nth-child(2) div:nth-child(2) a').click();
    cy.get('#root div:nth-child(2) > h3.font-semibold > a.no-underline').click();
    cy.get('#root button.mt-2 svg').click();
    cy.get('#root a.gap-2 span').click();
    cy.get('#root div:nth-child(1) > button:nth-child(2)').click();
    cy.get('#root div:nth-child(1) > button:nth-child(3)').click();
    cy.get('#root div:nth-child(6) a.no-underline').click();
    cy.get('#root a.hover\\:bg-emerald-950\\/40').click();
    cy.get('#root div.hidden a[href="/"]').click();
    cy.get('#root div:nth-child(4) div.items-center a').click();
    cy.get('#root span.cursor-pointer').click();
});